# Generated by Django 5.0.6 on 2024-08-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0002_codigo_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigo',
            name='code_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
