# Generated by Django 5.0.6 on 2024-08-05 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0003_codigo_code_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigo',
            name='code_content',
        ),
    ]
